{ ... }:

{



  boot = {
    # Bootloader.
    loader = {
      timeout = 2;

      grub = {
        enabled = true;
        device = "/dev/vda";
        useOSProber = true;
      };
    };

    # reduce the kernel console log messages, 
    # all Kernel Messages with a log level smaller than this setting will be printed to the console. 
    consoleLogLevel = 0;

    kernelParams = [
      "quiet" # disable kernel messages on boot
    ];

    # disable verbose initrd messages on boot
    # removes only the mandatory messages generated by the NixOS scripts
    # # https://search.nixos.org/options?channel=23.11&show=boot.initrd.verbose&from=0&size=50&sort=relevance&type=packages&query=initrd.verbose
    initrd.verbose = false;
  };
}
